name: PlusPy

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch.
  pull_request:
    branches:
      - master         # Pull requests opened on the master branch.

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      # Get PlusPy's sources from Github repository
      - uses: actions/checkout@v2

      # Run PlusPy's regression tests.
      - name: Run regression tests
        working-directory: ./tests/
        run: |
            echo $PWD
            which python3
            python3 --version
            ./regres.scr
